/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-19 07:13:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1596615471827L));
    _jspx_dependants.put("jar:file:/C:/MVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodeeCommunity/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/MVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodeeCommunity/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>구디 커뮤니티</title>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    \t<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\t<script src=\"index.js\" defer></script>\r\n");
      out.write("\t<script src=\"https://kit.fontawesome.com/fbff03f786.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tbackground-image: url('./image/backgroundimg2.png');\r\n");
      out.write("\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t.navbar__logo {\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 363px;\r\n");
      out.write("\t\ttop: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar__logo img {\r\n");
      out.write("\t    width: 150px;\r\n");
      out.write("\t\theight: 150px;\r\n");
      out.write("\t\tborder-radius: 50%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.joinbox{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 30%;\r\n");
      out.write("\t\ttop: 30%;\r\n");
      out.write("\t\twidth: 550px;\r\n");
      out.write("\t\theight: 400px;\r\n");
      out.write("\t\tborder: 3px solid rgb(148, 186, 201);\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t\tpadding-left: 70px;\r\n");
      out.write("\r\n");
      out.write("\t\tbackground-color: rgb(224, 220, 213);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttable, td,tr {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 5px 10px;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("         <div class=\"navbar__logo\">\r\n");
      out.write("                <a href=\"main\">\r\n");
      out.write("                    <img src=\"image/logo.PNG\" alt=\"로고\">\r\n");
      out.write("                 </a>\r\n");
      out.write("         </div>       \r\n");
      out.write("            \r\n");
      out.write("         <div class=\"joinbox\">\r\n");
      out.write("            <h3> 회원 가입 </h3>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> 아이디* </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"id\"/> <input type=\"button\" id=\"idChck\" value=\"ID중복확인\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> 비밀번호* </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"password\" name=\"pw\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> 비밀번호확인* </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"password\" name=\"pwChck\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> 닉네임* </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"nickName\"/> <input type=\"button\" id=\"nickChck\" value=\"중복확인\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> 이름* </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"name\"></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> 이메일 </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"email\" name=\"u_email\"> <button id=\"auth\">인증 코드 발송</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">인증 코드 입력 : <input type=\"text\" name=\"auth\"> <button id=\"authChk\">인증하기</button> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"> <input type = \"button\" id=\"join\" value=\"회원가입\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write(" \t<div class=\"helpIcon\">\r\n");
      out.write("        <i class=\"far fa-comment-dots\"></i>   \r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"helpIcon__content\">\r\n");
      out.write("        <div class=\"helpIcon__title\">\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <p>무엇을 도와드릴까요?</p>\r\n");
      out.write("            <p>문의 주신 내용은 확인 후 답변 드리겠습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"helpIcon__input\">\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <input type=\"text\" name=\"writer\" placeholder=\"   작성자\"> \r\n");
      out.write("            <input type=\"text\" name=\"subject\" placeholder=\"   제목\">\r\n");
      out.write("            <input type=\"text\" name=\"c_email\" placeholder=\"   이메일\">\r\n");
      out.write("            <textarea type=\"text\" name=\"content\" placeholder=\"     문의 내용\"></textarea>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <button id=\"ct_send\">보내기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("       \t\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var overChk = false;\r\n");
      out.write("var overChknic = false;\r\n");
      out.write("var dice = null;\r\n");
      out.write("var emailChk = 0;\r\n");
      out.write("\r\n");
      out.write("$(\"#auth\").click(function(){\r\n");
      out.write("\tif($(\"input[name='u_email']\").val() == \"\"){\r\n");
      out.write("\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar $email = $(\"input[name='u_email']\");\r\n");
      out.write("\t\tvar param = {};\r\n");
      out.write("\t\tparam.email = $email.val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\turl: \"mail\",\r\n");
      out.write("\t\t\tdata: param,\r\n");
      out.write("\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\talert(\"인증코드가 전송되었습니다. 이메일을 확인해주세요\");\r\n");
      out.write("\t\t\t\tdice = data.dice;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(error){\r\n");
      out.write("\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\t\t\t\t\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#authChk\").click(function(){\r\n");
      out.write("\tif($(\"input[name='auth']\").val() == dice){\r\n");
      out.write("\t\temailChk = 1;\r\n");
      out.write("\t\talert(\"인증번호가 확인되었습니다.\");\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\talert(\"인증번호를 다시 확인해주세요.\");\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#idChck\").click(function(){\r\n");
      out.write("\tif($(\"input[name='id']\").val() == \"\"){\r\n");
      out.write("\t\talert(\"아이디를 입력해주세요.\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar id = $(\"input[name='id']\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\turl: \"overlay\",\r\n");
      out.write("\t\t\tdata: {\"id\":id},\r\n");
      out.write("\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data.overlay){\r\n");
      out.write("\t\t\t\t\talert(\"이미 사용중인 ID 입니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"input[name='id']\").val(\"\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"사용 가능한 ID 입니다\");\r\n");
      out.write("\t\t\t\t\toverChk = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(e){\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#nickChck\").click(function(){\r\n");
      out.write("\tif($(\"input[name='nickName']\").val() == \"\"){\r\n");
      out.write("\t\talert(\"닉네임을 입력해주세요.\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar nickname = $(\"input[name='nickName']\").val(); // id값 가져오기\r\n");
      out.write("\t\tconsole.log(nickname); // 잘 들어오는 지 확인: 1차\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\turl: \"overlaynick\",\r\n");
      out.write("\t\t\tdata: {\"nickname\":nickname},\r\n");
      out.write("\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\tsuccess: function(data){\t\t\r\n");
      out.write("\t\t\t\tif(data.overlay){\r\n");
      out.write("\t\t\t\t\talert(\"이미 사용중인 닉네임입니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"input[name='nickName']\").val(\"\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"사용 가능한 닉네임입니다\");\r\n");
      out.write("\t\t\t\t\toverChknic = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(e){\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#join\").click(function(){\r\n");
      out.write("\tvar $id = $(\"input[name='id']\");\r\n");
      out.write("\tvar $pw = $(\"input[name='pw']\");\r\n");
      out.write("\tvar $pwChck = $(\"input[name='pwChck']\");\r\n");
      out.write("\tvar $name = $(\"input[name='name']\");\r\n");
      out.write("\tvar $nickName = $(\"input[name='nickName']\");\r\n");
      out.write("\tvar $email = $(\"input[name='u_email']\");\r\n");
      out.write("\tvar $emailChk =$(\"input[name='auth']\");\r\n");
      out.write("\t\r\n");
      out.write("\tconsole.log($id);\r\n");
      out.write("\tconsole.log($pw);\r\n");
      out.write("\tconsole.log($name);\r\n");
      out.write("\t\r\n");
      out.write("\tif($pw.val()==$pwChck.val()){}else{\r\n");
      out.write("\t\talert(\"비밀번호가 일치하지 않습니다.\")\r\n");
      out.write("\t\t$(\"input[name='pw]\").focus();\r\n");
      out.write("\t};\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif(overChk&&overChknic){\t\t\t\r\n");
      out.write("\t\tif($id.val()==\"\"){\r\n");
      out.write("\t\t\talert(\"아이디를 확인해주세요\");\r\n");
      out.write("\t\t\t$id.focus();\r\n");
      out.write("\t\t}else if($pw.val()==\"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t\t$pw.focus();\r\n");
      out.write("\t\t}else if($pwChck.val()==\"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 확인해주세요\");\r\n");
      out.write("\t\t\t$pwChck.focus();\r\n");
      out.write("\t\t}else if($nickName.val()==\"\"){\r\n");
      out.write("\t\t\talert(\"닉네임을 입력해주세요\");\r\n");
      out.write("\t\t}else if($name.val()==\"\"){\r\n");
      out.write("\t\t\talert(\"이름을 입력해주세요\");\r\n");
      out.write("\t\t\t$name.focus();\r\n");
      out.write("\t\t}else if($email.val()==\"\"){\r\n");
      out.write("\t\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\t\t$email.focus();\r\n");
      out.write("\t\t}else if(emailChk != 1){\r\n");
      out.write("\t\t\talert(\"이메일 인증을 완료해주세요.\");\r\n");
      out.write("\t\t\t$('#auth').focus();\r\n");
      out.write("\t\t}else{// 모든 항목을 입력했을 경우\r\n");
      out.write("\t\t\tconsole.log(\"서버로 전송\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar param = {};\r\n");
      out.write("\t\t\tparam.id = $id.val();\r\n");
      out.write("\t\t\tparam.pw = $pw.val();\r\n");
      out.write("\t\t\tparam.name = $name.val();\r\n");
      out.write("\t\t\tparam.nickName = $nickName.val();\r\n");
      out.write("\t\t\tparam.email = $email.val();\r\n");
      out.write("\t\t\tparam.emailChk = emailChk;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log('param:' , param); // 콘솔에 +찍으면 문자열로 바뀜\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\turl: \"join\",\r\n");
      out.write("\t\t\t\tdata: param,\r\n");
      out.write("\t\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data.join);\r\n");
      out.write("\t\t\t\t\tif(data.join){\r\n");
      out.write("\t\t\t\t\t\talert(\"회원가입에 성공하였습니다. \");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"main\";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"회원가입에 실패하였습니다.\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"joinform.jsp\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(error){\r\n");
      out.write("\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"중복체크를 확인해 주세요\");\r\n");
      out.write("\t\t$(\"input[name='id']\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//문의사항 보내기\r\n");
      out.write("$(\"#ct_send\").click(function(){\r\n");
      out.write("\r\n");
      out.write("\tvar param = {};\r\n");
      out.write("\t\r\n");
      out.write("\tparam.writer = $(\"input[name='writer']\").val();\r\n");
      out.write("\tparam.subject = $(\"input[name='subject']\").val();\r\n");
      out.write("\tparam.c_email = $(\"input[name='c_email']\").val();\r\n");
      out.write("\tparam.content = $(\"textarea[name='content']\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type: \"post\",\r\n");
      out.write("        url: \"contactWrite\",\r\n");
      out.write("        data: param,\r\n");
      out.write("        dataType: \"JSON\",\r\n");
      out.write("        success: function(data){\r\n");
      out.write("        \talert(data.contactmsg);\r\n");
      out.write("        \t$(\".helpIcon__content\").fadeOut();\r\n");
      out.write("        },\r\n");
      out.write("        error: function(error){\r\n");
      out.write("        \talert(data.contactmsg);\r\n");
      out.write("        }\r\n");
      out.write("     }); // 쓰기는 되는데 왜 원래 화면으로 안돌아오는 걸까?\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
