/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-19 07:15:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lunchmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1596615471827L));
    _jspx_dependants.put("jar:file:/C:/MVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodeeCommunity/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/MVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodeeCommunity/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@900&family=Source+Sans+Pro:wght@600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"D130_style.css\">\r\n");
      out.write("<script src=\"index.js\" defer></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("src=\"https://kit.fontawesome.com/fbff03f786.js\"\r\n");
      out.write("crossorigin=\"anonymous\"\r\n");
      out.write("></script>\r\n");
      out.write("<title>구디 커뮤니티</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("        <!-- Main Navbar -->\r\n");
      out.write("        <nav class=\"navbar\" id=\"navbar\">\r\n");
      out.write("            <div class=\"navbar__logo\">\r\n");
      out.write("                <a href=\"main\">\r\n");
      out.write("                    <img src=\"image/logo.PNG\" alt=\"로고\">\r\n");
      out.write("                    <h1>구디 커뮤니티</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"search-input\">\r\n");
      out.write("                <form class=\"searchbar\" action=\"search\" method=\"get\">\r\n");
      out.write("                    <input\r\n");
      out.write("                      class=\"search\"\r\n");
      out.write("                      type=\"text\"\r\n");
      out.write("                      name=\"search\"\r\n");
      out.write("                    />\r\n");
      out.write("                    <button><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\t\r\n");
      out.write("            \r\n");
      out.write("            <button class=\"write\" onclick=\"location.href='writeView'\">\r\n");
      out.write("                글쓰기\r\n");
      out.write("            </button>\r\n");
      out.write("    \r\n");
      out.write("            <ul class=\"navbar__menu\">\r\n");
      out.write("                <h2>전체 게시판</h2>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"boardList?mboard_no=1\">\r\n");
      out.write("                        <span>자유 게시판</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"boardList?mboard_no=2\">\r\n");
      out.write("                        <span>학습 게시판</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"boardList?mboard_no=3\">\r\n");
      out.write("                        <span>익명 게시판</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"lunchmenu.jsp\">\r\n");
      out.write("                        <span>오늘 점심 뭐먹지?</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("\t\t\t<div class=\"top-util\">\r\n");
      out.write("\t  \t\t\t<div id=\"profile_img\" class=\"boxx\">\r\n");
      out.write("\t       \t\t  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "upmy1.jsp", out, false);
      out.write("\r\n");
      out.write("\t   \t\t\t  </div>\r\n");
      out.write("\t           <div class=\"inner\">                    \r\n");
      out.write("\t               <button id=\"login\" class=\"login\" onclick=\"location.href='login.jsp'\">로그인</button>\r\n");
      out.write("\t           </div>\r\n");
      out.write("\t       </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Main Contents -->\r\n");
      out.write("        <div id=\"contents\">\r\n");
      out.write("            <!--오늘 점심 뭐먹지-->\r\n");
      out.write("            \t<div class=\"board-name\"><h3>오늘 점심 뭐먹지?</h3></div>\r\n");
      out.write("            <button class=\"menutype-select\">한식</button>\r\n");
      out.write("            <button class=\"menutype\">중식</button>\r\n");
      out.write("            <button class=\"menutype\">일식</button>\r\n");
      out.write("            <button class=\"menutype\">양식</button>\r\n");
      out.write("            <button class=\"menutype\">분식</button>\r\n");
      out.write("            <button class=\"menutype\">배달맛집</button>\r\n");
      out.write("\r\n");
      out.write("            <!--메인-->\r\n");
      out.write("            <div class=\"menu-board\">\r\n");
      out.write("                <div class=\"menu1\" style=\"cursor: pointer;\" onclick=\"location.href='https:store.naver.com/restaurants/detail?id=38675031';\">\r\n");
      out.write("                    <div class=\"menu-image1\">\r\n");
      out.write("                        <span class=\"koreamenu-name1\">동남부대찌개</span>\r\n");
      out.write("                        <img src=\"./image/전화아이콘.PNG\" class=\"telimg1\">\r\n");
      out.write("                        <span class=\"koreamenu-tel1\">02-867-0849</span>\r\n");
      out.write("                        <img src=\"./image/지도아이콘.PNG\" class=\"mapimg1\">\r\n");
      out.write("                        <div class=\"koreamenu-map1\">서울 금천구 가산디지털2로 142-3</div>\r\n");
      out.write("                        <div class=\"moresee1\">더보기 ></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("                <div class=\"menu2\" style=\"cursor: pointer;\" onclick=\"location.href='https:store.naver.com/restaurants/detail?id=1029449605';\">\r\n");
      out.write("                    <div class=\"menu-image2\">\r\n");
      out.write("                        <span class=\"koreamenu-name2\">육전국밥</span>\r\n");
      out.write("                        <img src=\"./image/전화아이콘.PNG\" class=\"telimg2\">\r\n");
      out.write("                        <span class=\"koreamenu-tel2\">02-854-8222</span>\r\n");
      out.write("                        <img src=\"./image/지도아이콘.PNG\" class=\"mapimg2\">\r\n");
      out.write("                        <div class=\"koreamenu-map2\">서울 금천구 가산디지털2로 136</div>\r\n");
      out.write("                        <div class=\"moresee2\">더보기 ></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"menu3\" style=\"cursor: pointer;\" onclick=\"location.href='http:store.naver.com/restaurants/detail?id=1001630614&query=%EB%AA%A8%EB%91%90%EA%B5%AD%EB%B0%A5';\">\r\n");
      out.write("                    <div class=\"menu-image3\">\r\n");
      out.write("                        <span class=\"koreamenu-name3\">모두국밥</span>\r\n");
      out.write("                        <img src=\"./image/전화아이콘.PNG\" class=\"telimg3\">\r\n");
      out.write("                        <span class=\"koreamenu-tel3\">02-2025-4123</span>\r\n");
      out.write("                        <img src=\"./image/지도아이콘.PNG\" class=\"mapimg3\">\r\n");
      out.write("                        <div class=\"koreamenu-map3\">서울 금천구 가산디지털2로 123</div>\r\n");
      out.write("                        <div class=\"moresee3\">더보기 ></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"menu4\" style=\"cursor: pointer;\" onclick=\"location.href='https:store.naver.com/restaurants/detail?id=21369601';\">\r\n");
      out.write("                    <div class=\"menu-image4\">\r\n");
      out.write("                        <span class=\"koreamenu-name4\">돈보따리</span>\r\n");
      out.write("                        <img src=\"./image/전화아이콘.PNG\" class=\"telimg4\">\r\n");
      out.write("                        <span class=\"koreamenu-tel4\">02-855-5550</span>\r\n");
      out.write("                        <img src=\"./image/지도아이콘.PNG\" class=\"mapimg4\">\r\n");
      out.write("                        <div class=\"koreamenu-map4\">서울 금천구 가산디지털2로 142-9</div>\r\n");
      out.write("                        <div class=\"moresee4\">더보기 ></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"menu5\" style=\"cursor: pointer;\" onclick=\"location.href='https:store.naver.com/restaurants/detail?id=34034063&tab=main';\">\r\n");
      out.write("                    <div class=\"menu-image5\">\r\n");
      out.write("                        <span class=\"koreamenu-name5\">토마토김밥</span>\r\n");
      out.write("                        <img src=\"./image/전화아이콘.PNG\" class=\"telimg5\">\r\n");
      out.write("                        <span class=\"koreamenu-tel5\">02-861-8484</span>\r\n");
      out.write("                        <img src=\"./image/지도아이콘.PNG\" class=\"mapimg5\">\r\n");
      out.write("                        <div class=\"koreamenu-map5\">서울 금천구 서부샛길 606</div>\r\n");
      out.write("                        <div class=\"moresee5\">더보기 ></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"list-box\">   \r\n");
      out.write("                    <div class=\"list-paging\">\r\n");
      out.write("                    <button id=\"1\" class=\"on\">1</button>\r\n");
      out.write("                    <button id=\"2\">2</button>\r\n");
      out.write("                    <button id=\"3\">3</button>\r\n");
      out.write("                    <button id=\"4\">4</button>\r\n");
      out.write("                    <button id=\"5\">5</button>\r\n");
      out.write("                    <button id=\"next\">next</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write(" <div class=\"helpIcon\">\r\n");
      out.write("        <i class=\"far fa-comment-dots\"></i>   \r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"helpIcon__content\">\r\n");
      out.write("        <div class=\"helpIcon__title\">\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <p>무엇을 도와드릴까요?</p>\r\n");
      out.write("            <p>문의 주신 내용은 확인 후 답변 드리겠습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"helpIcon__input\">\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <input type=\"text\" name=\"writer\" placeholder=\"   작성자\"> \r\n");
      out.write("            <input type=\"text\" name=\"subject\" placeholder=\"   제목\">\r\n");
      out.write("            <input type=\"text\" name=\"c_email\" placeholder=\"   이메일\">\r\n");
      out.write("            <textarea type=\"text\" name=\"content\" placeholder=\"     문의 내용\"></textarea>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <button id=\"ct_send\">보내기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\tvar loginId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tvar profile_img = $(\"#profile_img\");\r\n");
      out.write("\t\tvar loginbtn = $(\"#login\");\r\n");
      out.write("\t\tif(loginId==\"\"){\r\n");
      out.write("\t\t\tprofile_img.css({\"display\":\"none\"});\t\r\n");
      out.write("\t\t}else{    \r\n");
      out.write("\t\t    loginbtn.css({\"display\":\"none\"});\r\n");
      out.write("\t\t    profile_img.css({\"display\":\"block\"});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//문의사항 보내기\r\n");
      out.write("\t\t$(\"#ct_send\").click(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar param = {};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tparam.writer = $(\"input[name='writer']\").val();\r\n");
      out.write("\t\t\tparam.subject = $(\"input[name='subject']\").val();\r\n");
      out.write("\t\t\tparam.c_email = $(\"input[name='c_email']\").val();\r\n");
      out.write("\t\t\tparam.content = $(\"textarea[name='content']\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t        type: \"post\",\r\n");
      out.write("\t\t        url: \"contactWrite\",\r\n");
      out.write("\t\t        data: param,\r\n");
      out.write("\t\t        dataType: \"JSON\",\r\n");
      out.write("\t\t        success: function(data){\r\n");
      out.write("\t\t        \talert(data.contactmsg);\r\n");
      out.write("\t\t        \t$(\".helpIcon__content\").fadeOut();\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        error: function(error){\r\n");
      out.write("\t\t        \talert(data.contactmsg);\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t     }); // 쓰기는 되는데 왜 원래 화면으로 안돌아오는 걸까?\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
