/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-19 08:36:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class searchidpass_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1596615471827L));
    _jspx_dependants.put("jar:file:/C:/MVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodeeCommunity/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/MVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GoodeeCommunity/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>구디 커뮤니티</title>\r\n");
      out.write("\t<script src = \"https://code.jquery.com/jquery-3.5.1.min.js\"> </script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\t<script src=\"index.js\" defer></script>\r\n");
      out.write("\t<script src=\"https://kit.fontawesome.com/fbff03f786.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.navbar__logo {\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 363px;\r\n");
      out.write("\t\ttop: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar__logo img {\r\n");
      out.write("\t    width: 150px;\r\n");
      out.write("\t\theight: 150px;\r\n");
      out.write("\t\tborder-radius: 50%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.searchbox{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 30%;\r\n");
      out.write("\t\ttop: 30%;\r\n");
      out.write("\t\tborder: 3px solid rgb(148, 186, 201);\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t\tbackground-color: rgb(224, 220, 213);\r\n");
      out.write("\t\twidth: 735px;\r\n");
      out.write("\t\theight: 365px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.searchboxx{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tleft: 50px;\r\n");
      out.write("\t\ttop: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttable, tr, td{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tbackground-image: url('./image/backgroundimg3.png');\r\n");
      out.write("\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"navbar__logo\">\r\n");
      out.write("            <a href=\"main\">\r\n");
      out.write("                <img src=\"image/logo.PNG\" alt=\"로고\">\r\n");
      out.write("             </a>\r\n");
      out.write("    </div>           \r\n");
      out.write("\r\n");
      out.write("\t<div class= \"searchbox\">\r\n");
      out.write("\t\t<div class=\"searchboxx\">\r\n");
      out.write("\t\t\t<h2> ID 찾기</h2>\t\t\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t이메일을 입력해주세요\r\n");
      out.write("\t\t\t\t\t<input type=\"email\" id=\"email\"> <button id=\"findid\" onclick=\"findid()\">ID 찾기</button>\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<h2> 비밀번호 찾기</h2>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<p>이메일을 입력해주세요. 입력하신 이메일로 임시 비밀번호를 발송해드립니다.</p>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<p><td>이메일 : <input type=\"email\" name=\"u_email\"> <button id=\"auth\">임시비밀번호 발송</button></td></p>\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"helpIcon\">\r\n");
      out.write("        <i class=\"far fa-comment-dots\"></i>   \r\n");
      out.write("    </div>  \r\n");
      out.write("    <div class=\"helpIcon__content\">\r\n");
      out.write("        <div class=\"helpIcon__title\">\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <p>무엇을 도와드릴까요?</p>\r\n");
      out.write("            <p>문의 주신 내용은 확인 후 답변 드리겠습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"helpIcon__input\">\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <input type=\"text\" placeholder=\"   작성자\"> \r\n");
      out.write("            <input type=\"text\" placeholder=\"   제목\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"   이메일\">\r\n");
      out.write("            <textarea type=\"text\" placeholder=\"     문의 내용\"></textarea>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <button>보내기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\t\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"#auth\").click(function(){\r\n");
      out.write("\t\tif($(\"input[name='u_email']\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar $u_email = $(\"input[name='u_email']\");\r\n");
      out.write("\t\t\tvar param = {};\r\n");
      out.write("\t\t\tparam.email = $u_email.val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\turl: \"findpw\",\r\n");
      out.write("\t\t\t\tdata: param,\r\n");
      out.write("\t\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\talert(data.msg);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(error){\r\n");
      out.write("\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\t\t\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction findid(){\r\n");
      out.write("\t\tvar email = $(\"#email\").val();\r\n");
      out.write("\t\tconsole.log(email); // 잘 들어오는 지 확인: 1차\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\turl: \"findid\",\r\n");
      out.write("\t\t\tdata: {\"email\":email},\r\n");
      out.write("\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data.searchedid);\r\n");
      out.write("\t\t\t\tvar id = data.searchedid;\r\n");
      out.write("\t\t\t\tconsole.log(id);\r\n");
      out.write("\t\t\t\tif(id!==\"\"){alert(\"회원님의 아이디는: \"+id+\"입니다.\");}\r\n");
      out.write("\t\t\t\telse{alert(\"입력하신 이메일로 가입된 정보가 없습니다.\");}\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(e){\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//문의사항 보내기\r\n");
      out.write("\t$(\"#ct_send\").click(function(){\r\n");
      out.write("\r\n");
      out.write("\t\tvar param = {};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tparam.writer = $(\"input[name='writer']\").val();\r\n");
      out.write("\t\tparam.subject = $(\"input[name='subject']\").val();\r\n");
      out.write("\t\tparam.c_email = $(\"input[name='c_email']\").val();\r\n");
      out.write("\t\tparam.content = $(\"textarea[name='content']\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t        type: \"post\",\r\n");
      out.write("\t        url: \"contactWrite\",\r\n");
      out.write("\t        data: param,\r\n");
      out.write("\t        dataType: \"JSON\",\r\n");
      out.write("\t        success: function(data){\r\n");
      out.write("\t        \talert(data.contactmsg);\r\n");
      out.write("\t        \t$(\".helpIcon__content\").fadeOut();\r\n");
      out.write("\t        },\r\n");
      out.write("\t        error: function(error){\r\n");
      out.write("\t        \talert(data.contactmsg);\r\n");
      out.write("\t        }\r\n");
      out.write("\t     }); // 쓰기는 되는데 왜 원래 화면으로 안돌아오는 걸까?\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
